### ISSUE TITLE
requiring malt stops plotting function from printing lines

### ISSUE THREAD

**Issue by dr-neptune** [themetaschemer/malt#16]
Hi, when loading `malt` the line plotting functionality in racket seems to break.

Here is an example of it breaking:

```scheme
#lang racket
(require plot malt)
(plot-new-window? #t)

(plot (function (λ (x) (* x x)) #:color "blue")
      #:x-min -10 #:x-max 10
      #:y-min 0 #:y-max 100
      #:title "y = x^2")
```

![image](https://user-images.githubusercontent.com/15676822/225305897-cee354b6-5d82-4f07-a686-709992d0f3dd.png)

and an example of it working:

```scheme
(require racket plot)
(plot-new-window? #t)

(plot (function (λ (x) (* x x)) #:color "blue")
      #:x-min -10 #:x-max 10
      #:y-min 0 #:y-max 10)
```

![image](https://user-images.githubusercontent.com/15676822/225306266-ad4171c0-3a00-4682-864f-2048868c4c81.png)

Curiously, plotting points with `malt` loaded still works even though the line breaks:

```scheme
(define line-xs
  '(2.0 1.0 4.0 3.0))

(define line-ys
  '(1.8 1.2 4.2 3.3))

(plot (list (points (map vector line-xs line-ys) #:color "mediumpurple")
            (function (λ (x) (* x x)) #:color "blue"))
      #:x-min 0 #:x-max 10
      #:y-min 0 #:y-max 10)
```

![image](https://user-images.githubusercontent.com/15676822/225306566-486ac976-a857-45e2-ba36-6a78df6b600b.png)

and even more curious, certain functions that use line also work with `malt` loaded:

```scheme
(plot (list (points (map vector line-xs line-ys) #:color "mediumpurple")
            (function sin 0 5 #:color "blue"))
      #:x-min 0 #:x-max 5
      #:y-min 0 #:y-max 5)
```

![image](https://user-images.githubusercontent.com/15676822/225307010-2de4e95d-c26a-4721-88a5-629f60744921.png)

**Comment by dr-neptune** [comment]
That makes sense to me, but unfortunately the following still shows a blank canvas:

```scheme
#lang racket
(require plot (rename-in malt (line malt-line)))
(plot-new-window? #t)

(plot (function (λ (x) (* x x)) #:color "blue")
      #:x-min -10 #:x-max 10
      #:y-min 0 #:y-max 100
      #:title "y = x^2")
```

**Comment by themetaschemer** [comment]
It is probably due to the fact that * is overrriden to enable automatic differentiation. Try invoking (\rho (* x x)) in your plotting function.

**Comment by dr-neptune** [comment]
success! Thank you!
