### ISSUE TITLE
Infinite loop while trying to print `(tensor)` using learner implementation

### ISSUE THREAD

**Issue by DarshalShetty** [themetaschemer/malt#29]
Steps to reproduce:
- Switch implementation to "learner"
- Run `make clean && make bulld`
- Open a Racket REPL and require the `main.rkt` file
- Evaluate `(tensor)`

Instead of raising an error or returning an empty vector, evaluating `(tensor)` goes into an infinite loop. This may be caused while trying to pretty print the tensor in `ports.rkt`.

**Comment by themetaschemer** [comment]
Fixed in https://github.com/themetaschemer/malt/commit/6c9e105db0c8b4a086567d12ddb2c5ab6de091c9
