### ISSUE TITLE
Requiring `malt` causes RackUnit's checks to fail

### ISSUE THREAD

**Issue by bmitc** [themetaschemer/malt#3]
I am writing Racket code along with *The Little Learner*, including writing tests to check and verify things as I go along using [RackUnit](https://docs.racket-lang.org/rackunit/index.html). (I did the same for *The Little Schemer*: [bmitc/the-little-schemer](https://github.com/bmitc/the-little-schemer).) However, upon placing `(require malt)` in my file, both `check-equal?` and `check-=` fail in ways that don't make any sense, in terms of what is reported back.

For example, I have the code:
```racket
#lang racket

(require malt)

;; Frame 9
;(define line
;  (λ (x)
;    (λ (w b)
;      (let ([y (+ (* w x) b)])
;        y))))

;; Frame 11
(define line
  (λ (x)
    (λ (w b)
      (+ (* w x) b))))

;; Frame 17
;; The book's code is not executable, as the expressions aren't lists.
;; Here, they are quoted to turn them into lists.
(define line-xs '[2.0 1.0 4.0 3.0])
(define line-ys '[1.8 1.2 4.2 3.3])

(module+ test
  (require rackunit)

  ;; Frame 14
  (check-equal? ((line 8) 4 6) 38)

  ;; Frame 22
  (check-= ((line 3.79) 1.0 0.0) 3.79 0.0001)
  )
```

The tests pass if `(require malt)` is commented out. However, as it is, the following failures are returned upon running the file in DrRacket, which automatically executes the tests in the special `test` module:

```racket
--------------------
. FAILURE
name:       check-equal?
location:   chapter-01.rkt:29:2
actual:     38
expected:   38
--------------------
--------------------
. ..\..\..\..\Program Files\Racket\share\pkgs\rackunit-lib\rackunit\private\check.rkt:137:16: ERROR
name:       check-=
location:   chapter-01.rkt:32:2
params:     '(3.79 3.79 0.0001)

-: contract violation
  expected: number?
  given: 3.79
--------------------
```

Neither test failure makes any sense. Also, if I run `(number? 3.79)` in the REPL, I get `#t` as expected, so I don't know how the contract is failing.

I am assuming that the `malt` package re-defines several primitives / built-in functions in Racket, but it would be great if these worked with the RackUnit tests. I do not know where things are exactly going wrong, but the way this surfaces is confusing.

**Comment by themetaschemer** [comment]
Thanks for reporting this issue, @bmitc. This, however, is expected behaviour. Because of automatic differentiation, numbers are represented as duals which is what is causing this behavior. I will put a note regarding this in the README and in the accompanying documentation.  As a replacement for check-=, you can use check-dual-equal? In the meantime, let me see if I can figure out a way to override or augment check-= suitably.

**Comment by themetaschemer** [comment]
Also, check-dual-equal? does check for equality within a tolerance of 0.0001 (currently fixed).

**Comment by themetaschemer** [comment]
Here's the releveant documentation for check-dual-equal? 
https://docs.racket-lang.org/malt/Utilities.html

**Comment by themetaschemer** [comment]
Also, @bmitc, Look at the Notations page xxiii , for how to transcribe to racket. Where the book says `[1 2 3]`, for example, you will need to say `(tensor 1 2 3)`.

**Comment by bmitc** [comment]
Ah, thank you! Apologies for missing both of these in the documentation! I had read the notations page but somehow missed the connection once I got into things.

And `check-dual-equal?` will work fine. 👍 Although, it seems, naively, that the normal number checks should work for duals in which the dual part is 0. If not, is there a way to handle the contracts underneath such that the failures more accurately report the issue? Or the printing that could point to the problem more readily? That's one reason I didn't think to check for something like `check-dual-equal?` (that and I'm early in the book). For example, something like `expected number?, given dual?`?

I'm not deeply familiar with Racket's contract system and am not at a computer to play around with `dual?` and `scalar?`. But for now, the `check-dual-equal? certainly solves the issue of wanting to test things.

Thanks again! And thanks for the book. 🙂 Looking forward to the rest of it.
