### ISSUE TITLE
Learner allows constructing invalid tensors

### ISSUE THREAD

**Issue by sporkl** [themetaschemer/malt#33]
It looks like the learner representation allows constructing invalid tensors:
```racket
> (require malt/learner)
> (tensor (tensor 6.0 5.0 4.0) (tensor 3.0 2.0) (tensor 1.0))
'#(#(6.0 5.0 4.0) #(3.0 2.0) #(1.0))
> (tensor? (tensor (tensor 6.0 5.0 4.0) (tensor 3.0 2.0) (tensor 1.0)))
#t
```
Implementing `tensor` as a thin wrapper around vector does simplify things for appendix A, but the fact that the above code worked was confusing for a student. Given that there's already some wrapping around the implementation of `tensor`, I think it would make sense to check the validity of the tensor as well, like nested and flat tensors do.

I'd be up to working on and submitting a pull request for this!

**Comment by themetaschemer** [comment]
Go for it!
Thanks,
A.


Sent from Yahoo Mail for iPhone


On Thursday, June 29, 2023, 11:56 AM, Dmitri Volkov ***@***.***> wrote:




It looks like the learner representation allows constructing invalid tensors:
> (require malt/learner)
> (tensor (tensor 6.0 5.0 4.0) (tensor 3.0 2.0) (tensor 1.0))
'#(#(6.0 5.0 4.0) #(3.0 2.0) #(1.0))
> (tensor? (tensor (tensor 6.0 5.0 4.0) (tensor 3.0 2.0) (tensor 1.0)))
#t
Implementing tensor as a thin wrapper around vector does simplify things for appendix A, but the fact that the above code worked was confusing for a student. Given that there's already some wrapping around the implementation of tensor, I think it would make sense to check the validity of the tensor as well, like nested and flat tensors do.

I'd be up to working on and submitting a pull request for this!
