### ISSUE TITLE
Empty tensor

### ISSUE THREAD

**Issue by davidgrenier** [themetaschemer/malt#38]
Hello,

I'm unclear whether empty tensor shouldn't be a thing, but I had been having trouble because (vector) and (build-vector 0) would never return.

I've since figured (tlen (vector)) properly returned 0 and the issue might be with pretty printing empty tensor.

**Comment by themetaschemer** [comment]
Yes, if you have the latest malt, you won't be able to build an empty tensor. You can, of course, fake it with an empty vector in some representations, but yes, there is a known pretty printing bug on the "empty" tensor.
