### ISSUE TITLE
Malt Installation Failure

### ISSUE THREAD

**Issue by ednospam** [themetaschemer/malt#4]
Malt installation failure using raco

 $ raco pkg install malt
Resolving "malt" via https://download.racket-lang.org/releases/7.9/catalog/
Resolving "malt" via https://pkgs.racket-lang.org
Using cached16773510941677351094591 for https://github.com/themetaschemer/malt.git
build-path: contract violation
  expected: (or/c path-for-some-system? path-string? 'up 'same)
  given: #rx"test\\\\"
  argument position: 2nd
  other arguments...:
   #<path:/var/tmp/16773512881677351288189-themetaschemer_malt_git_master>
  context...:
   /usr/share/racket/collects/pkg/private/addl-installs.rkt:28:2: loop
   /usr/share/racket/collects/pkg/private/stage.rkt:107:0: stage-package/info
   /usr/share/racket/collects/pkg/private/stage.rkt:300:11
   /usr/share/racket/collects/pkg/private/stage.rkt:107:0: stage-package/info
   [repeats 1 more time]
   /usr/share/racket/collects/pkg/private/install.rkt:141:0: install-packages
   /usr/share/racket/collects/pkg/private/install.rkt:925:4
   /usr/share/racket/collects/racket/private/more-scheme.rkt:206:2: call-handled-body
   /usr/share/racket/collects/pkg/private/prefetch.rkt:54:0: call-with-prefetch-cleanup
   /usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt:555:3
   /usr/share/racket/collects/racket/file.rkt:437:8
   /usr/share/racket/collects/racket/private/kw-file.rkt:116:2: call-with-output-file*
   /usr/share/racket/collects/racket/file.rkt:426:0: call-with-file-lock
   /usr/share/racket/collects/pkg/main.rkt:216:16
   /usr/share/racket/collects/racket/private/more-scheme.rkt:206:2: call-handled-body

Environment
linux raspberrypi 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/Linux
Racket v7.9 [bc]

Racket was installed using apt get-install racket. There doesn't seem to be an ARM64 package for Racket on the Racket download link provided.  

If this is a version skew problem, perhaps a warning to avoid versions older than N, or ARM64  should be added to the instructions or in the installation script.

**Comment by themetaschemer** [comment]
Thanks for also reporting this issue @ednospam. The resolution here is similar to #5 -- upgrade to Racket 8.2 or higher. I will update the package metadata to reflect this as well.

**Comment by themetaschemer** [comment]
Added checks in commit [be9224c](https://github.com/themetaschemer/malt/commit/be9224c097bacba620c4c622b90acc638ab31462)
