### ISSUE TITLE
Should be `apply-flat-∇-fn-2`

### ISSUE THREAD

**Issue by emiruner** [themetaschemer/malt#42]
Shouldn't `apply-flat-∇-fn-2` be called in this line instead of `apply-flat-∇-fn-1`?

https://github.com/themetaschemer/malt/blob/407b2f817b200da6322df66b9c6b91c423017efe/flat-tensors/autodiff/B-prims.rkt#L111

**Comment by themetaschemer** [comment]
Yes, you are correct! Thanks for pointing it out. Seems to have escaped our tests.
