### ISSUE TITLE
[learner] tlen doesn't handle scalars

### ISSUE THREAD

**Issue by soegaard** [themetaschemer/malt#46]
There is a discrepancy between the documentation of `tlen` and the learner implementation.
The documentation shows that `tlen` takes any tensor as input.

<img width="800" alt="image" src="https://github.com/themetaschemer/malt/assets/461765/58307bd6-71d7-46f6-b141-42c75b4e4477">

But the implementation of `tlen` doesn't handle scalars.

<img width="663" alt="image" src="https://github.com/themetaschemer/malt/assets/461765/1997d3a9-c595-4a0a-9016-22f6d979b83e">

**Comment by soegaard** [comment]
I suspect other functions in `B-tensor-basics.rkt` have the same problem.

**Comment by themetaschemer** [comment]
Thanks for pointing this out. We need to correct the documentation. `tlen` is not defined on scalars. It is technically equivalent to `(car (shape t))` which will be undefined for scalars since their shapes are the empty list. I'll check the other functions as well.

**Comment by soegaard** [comment]
In that case, the error mesage needs to be "tlen is not defined for scalars" instead of (for the user) an unrelated `vector-length` error.
